import { Inter } from "next/font/google";
import "../globals.css";
import estedadFont from "@/constants/localFonts";

//? import components
import Header from "@/app/(home)/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${estedadFont.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
