import { Inter } from "next/font/google";
import "../../globals.css";
import estedadFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";

//? import components
import Provider from "@/app/Providers";
import SideBar from "@/app/(profile)/profile/SideBar";
import Header from "@/app/(profile)/profile/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${estedadFont.variable} font-sans relative`}
      >
        <Provider>
          <Toaster position="top-center" />
          <Header />
          <div className="grid grid-cols-6 bg-white h-screen">
            <div className="hidden md:block md:col-span-2 lg:col-span-1 bg-blue-gray overflow-y-auto ">
              <SideBar />
            </div>
            <div className="col-span-6 md:col-span-4 lg:col-span-5 p-4 bg-white">
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
