import { Inter } from "next/font/google";
import "../../globals.css";
import estedadFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";

//? import components
import Provider from "@/app/Providers";
import Header from "@/app/(admin)/admin/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${estedadFont.variable} font-sans relative`}
      >
        <Provider>
          <Toaster position="top-center" />
          <Header>{children}</Header>
        </Provider>
      </body>
    </html>
  );
}
