import { Inter } from "next/font/google";
import "../../globals.css";
import estedadFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";

//? import components
import Provider from "@/app/Providers";
import SideBar from "@/app/(admin)/admin/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${estedadFont.variable} font-sans`}
      >
        <Provider>
          <Toaster position="top-center" />
          <div className="grid grid-cols-6 bg-white h-screen">
            <div className="col-span-1 bg-white overflow-y-auto">
              <SideBar />
            </div>
            <div className="col-span-5 overflow-y-auto p-4 bg-gray-100">
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
