export const AddPropertyInputs = [
  {
    id: 1,
    label: "price",
    type: "Number",
    name: "price",
    placeholder: "price ...",
  },
  {
    id: 2,
    label: "Monthly administrative fees",
    type: "Number",
    name: "monthly_administrative_fees",
    placeholder: "Monthly administrative fees ...",
  },
  {
    id: 3,
    label: "Room Number",
    type: "Select",
    name: "room",
    placeholder: "Select room Number ...",
  },
  {
    id: 4,
    label: "Gross area",
    type: "Number",
    name: "gross",
    placeholder: "Gross area ...",
  },
  {
    id: 5,
    label: "Net area",
    type: "Number",
    name: "net",
    placeholder: "Net area ...",
  },
  {
    id: 6,
    label: "Bathroom",
    type: "Select",
    name: "bathroom",
    placeholder: "Select Bathroom ...",
  },
  {
    id: 7,
    label: "Building age",
    type: "Number",
    name: "age",
    placeholder: "Building age ...",
  },
  {
    id: 8,
    label: "Building total floors",
    type: "Select",
    name: "total_floor",
    placeholder: "Building total floors ...",
  },
  {
    id: 9,
    label: "Floor",
    type: "Number",
    name: "floor",
    placeholder: "Floor ...",
  },
  {
    id: 10,
    label: "Building name",
    type: "Text",
    name: "name",
    placeholder: "Building name ...",
  },
  {
    id: 11,
    label: "Parking",
    type: "Number",
    name: "parking",
    placeholder: "Parking ...",
  },
  {
    id: 12,
    label: "Property profile",
    type: "Checkbox",
    name: "view",
    placeholder: "Select property profile ...",
  },
  {
    id: 13,
    label: "Building status",
    type: "Select",
    name: "building_status",
    placeholder: "Select Building status ...",
  },
  {
    id: 21,
    label: "Completion date",
    type: "Select",
    name: "completion_date",
    placeholder: "Select Completion date ...",
  },
  {
    id: 14,
    label: "Furnished",
    type: "Select",
    name: "furnished",
    placeholder: "Select Furnished ...",
  },
  {
    id: 15,
    label: "Title deed type",
    type: "Select",
    name: "title_deed",
    placeholder: "Select Title deed type ...",
  },
  {
    id: 16,
    label: "Using status",
    type: "Select",
    name: "using_status",
    placeholder: "Select Using status ...",
  },
  {
    id: 17,
    label: "Other features",
    type: "Checkbox",
    name: "another_features",
    placeholder: "Select Other features ...",
  },
  {
    id: 18,
    label: "Countries",
    type: "Select",
    name: "country",
    placeholder: "Select Countries ...",
  },
  {
    id: 19,
    label: "City",
    type: "Select",
    name: "city",
    placeholder: "Select City ...",
  },
  {
    id: 20,
    label: "Province",
    type: "Select",
    name: "province",
    placeholder: "Select Province ...",
  },
];
