export const AddPropertyInputs = [
  {
    id: 1,
    label: "price",
    type: "Number",
    name: "price",
    placeholder: "price ...",
    required: true,
    requiredError: "Price is required field",
  },
  {
    id: 2,
    label: "Monthly administrative fees",
    type: "Number",
    name: "monthly_administrative_fees",
    placeholder: "Monthly administrative fees ...",
    required: true,
    requiredError: "Monthly administrative is required field",
  },
  {
    id: 3,
    label: "Room Number",
    type: "Select",
    name: "room",
    placeholder: "Select room Number ...",
    required: true,
    requiredError: "Room is required field",
  },
  {
    id: 4,
    label: "Gross area",
    type: "Number",
    name: "gross",
    placeholder: "Gross area ...",
    required: true,
    requiredError: "Gross area is required field",
  },
  {
    id: 5,
    label: "Net area",
    type: "Number",
    name: "net",
    placeholder: "Net area ...",
    required: true,
    requiredError: "Net area is required field",
  },
  {
    id: 6,
    label: "Bathroom",
    type: "Select",
    name: "bathroom",
    placeholder: "Select Bathroom ...",
    required: true,
    requiredError: "Bathroom is required field",
  },
  {
    id: 7,
    label: "Building age",
    type: "Number",
    name: "age",
    placeholder: "Building age ...",
    required: true,
    requiredError: "Building age is required field",
  },
  {
    id: 8,
    label: "Building total floors",
    type: "Select",
    name: "total_floor",
    placeholder: "Building total floors ...",
    required: true,
    requiredError: "Building total floors is required field",
  },
  {
    id: 9,
    label: "Floor",
    type: "Number",
    name: "floor",
    placeholder: "Floor ...",
    required: true,
    requiredError: "Floor is required field",
  },
  {
    id: 10,
    label: "Building name",
    type: "Text",
    name: "name",
    placeholder: "Building name ...",
  },
  {
    id: 11,
    label: "Parking",
    type: "Number",
    name: "parking",
    placeholder: "Parking ...",
    required: true,
    requiredError: "Parking is required field",
  },
  {
    id: 12,
    label: "Property profile",
    type: "Checkbox",
    name: "view",
    placeholder: "Select property profile ...",
    required: true,
    requiredError: "Property profile is required field",
  },
  {
    id: 13,
    label: "Building status",
    type: "Select",
    name: "building_status",
    placeholder: "Select Building status ...",
    required: true,
    requiredError: "Building status is required field",
  },
  {
    id: 21,
    label: "Completion date",
    type: "Select",
    name: "completion_date",
    placeholder: "Select Completion date ...",
    required: true,
    requiredError: "Completion date is required field",
  },
  {
    id: 14,
    label: "Furnished",
    type: "Select",
    name: "furnished",
    placeholder: "Select Furnished ...",
    required: true,
    requiredError: "Furnished is required field",
  },
  {
    id: 15,
    label: "Title deed type",
    type: "Select",
    name: "title_deed",
    placeholder: "Select Title deed type ...",
    required: true,
    requiredError: "Title deed type is required field",
  },
  {
    id: 16,
    label: "Using status",
    type: "Select",
    name: "using_status",
    placeholder: "Select Using status ...",
    required: true,
    requiredError: "Using status is required field",
  },
  {
    id: 17,
    label: "Other features",
    type: "Checkbox",
    name: "another_features",
    placeholder: "Select Other features ...",
  },
  {
    id: 18,
    label: "Countries",
    type: "Select",
    name: "country",
    placeholder: "Select Countries ...",
    required: true,
    requiredError: "Country is required field",
  },
  {
    id: 19,
    label: "City",
    type: "Select",
    name: "city",
    placeholder: "Select City ...",
    required: true,
    requiredError: "City is required field",
  },
  {
    id: 20,
    label: "Province",
    type: "Select",
    name: "province",
    placeholder: "Select Province ...",
    required: true,
    requiredError: "province is required field",
  },
];
