import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import estedadFont from "@/constants/localFonts";

//? import components
import Header from "@/app/(home)/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${estedadFont.variable} font-sans`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
