import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import estedadFont from "@/constants/localFonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${estedadFont.variable} font-sans`}>{children}</body>
    </html>
  );
}
